[build]
  publish = "."
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "."
    baseUrl = "https://lightningautoservice.com"
    prettyURLs = false
    changeFreq = "monthly"
    priority = 0.7
    exclude = [
      "./service.html"
    ]

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
